### PR TITLE
 Solve issue when scroll down

### PR DESCRIPTION
**Pull request by allipierre**
When you scroll down , the Notification menu disappears

### CODE REVIEW

**Comment by allipierre** [comment]
Hi Ronny,
here is a example. Just scroll down https://apex.oracle.com/pls/apex/f?p=15755:1

**Comment by RonnyWeiss** [comment]
Hello

Thank you this tip I will add it to new release of the plug-in!

Kind Regards

Ronny

**Comment by allipierre** [comment]
Hi Ronny,

great!

Regards
Pierre

**Comment by allipierre** [comment]
Hi Ora-solution,

yes. Just run the DA more Time

Demo:

https://apex.oracle.com/pls/apex/f?p=15755:1


but it does not have to be that way. It's a bad design in my opinion. But the Plugin is cool. ;)

**Comment by Ora-solution** [comment]
Thank you Allipierre for your prompt response.

**Pull request closed without merging**
